#!/usr/bin/env node
// Bake the LIVE TIER into data/readings_seed.js (2026-09-21).
//
// A fresh device used to open on a pre-formula seed draft (prismdb.js carried
// six 2026-02 case studies) while the real Readings arrived later, over the
// GitHub contents API. Under the ruled floor the portal's first paint should be
// the live tier and nothing else — so the ten (or however many) files in
// data/readings/*.json are bundled here, with their git blob shas, and
// PrismDB.seed() imports them. The sync pull still runs on load and only
// refetches a file whose sha moved.
//
//   node scripts/bake-seed.js            # rewrites data/readings_seed.js
//
// Re-run after any change to the live tier (a promotion, a redraft, a retire).
const fs = require('fs'), path = require('path'), crypto = require('crypto');
const ROOT = path.resolve(__dirname, '..');
const DIR  = path.join(ROOT, 'data', 'readings');
const OUT  = path.join(ROOT, 'data', 'readings_seed.js');

const files = fs.readdirSync(DIR).filter(f => f.endsWith('.json')).sort();
const seed = files.map(f => {
  const buf = fs.readFileSync(path.join(DIR, f));
  const reading = JSON.parse(buf.toString('utf8'));
  const rid = f.replace(/\.json$/, '');
  if (!reading.rid) reading.rid = rid;                          // filename is authoritative (same rule as the pull)
  // git blob sha of the file as committed — matches what the contents API reports
  const sha = crypto.createHash('sha1').update('blob ' + buf.length + '\0').update(buf).digest('hex');
  return { rid, sha, reading };
});

const banner =
`// GENERATED by scripts/bake-seed.js — do not edit by hand.
// The live tier (data/readings/*.json) bundled for first paint; ${seed.length} Reading(s).
// Baked ${new Date().toISOString()}.
`;
fs.writeFileSync(OUT, banner + 'window.PRISM_SEED_READINGS = ' + JSON.stringify(seed) + ';\n');
console.log('baked ' + seed.length + ' Reading(s) → ' + path.relative(ROOT, OUT) +
  ' (' + Math.round(fs.statSync(OUT).size / 1024) + ' KB)');
seed.forEach(s => console.log('  ' + s.rid + '  ' + s.sha.slice(0, 7) + '  ' + (s.reading.title || '')));
